axis_linear: 1
scale_linear: 1.0
scale_linear_turbo: 1.5

axis_angular: 0
scale_angular: 0.5
scale_angular_turbo: 0.8

enable_button: 6  # L2 shoulder button
enable_turbo_button: 7  # L1 shoulder button
