axis_linear: 1
scale_linear: 0.3
scale_linear_turbo: 0.6

axis_angular: 0
scale_angular: 0.4
scale_angular_turbo: 0.6

enable_button: 4  # L2 shoulder button
enable_turbo_button: 5  # L1 shoulder button
