axis_linear: 1
scale_linear: 0.4
scale_linear_turbo: 1.2

axis_angular: 0
scale_angular: 0.5
scale_angular_turbo: 1

enable_button: 4  # L2 shoulder button
enable_turbo_button: 5  # L1 shoulder button
